name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token:   ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id:  ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args:    '--prod'

      - name: Health check
        # VERCEL_URL is automatically set by the action to the deployed hostname
        run: |
          URL="https://$VERCEL_URL"
          echo "🌐 Testing $URL"
          curl -fsSL "$URL" || (echo "❌ Health check failed" && exit 1)
