name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Disable cache due to npm optional dependencies bug

      - name: Clear npm cache and node_modules
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf frontend/node_modules  
          rm -rf backend/node_modules
          rm -f package-lock.json
          rm -f frontend/package-lock.json
          rm -f backend/package-lock.json

      - name: Install dependencies with force rebuild
        run: |
          npm install --force
          npm rebuild
          
      - name: Fix Rollup native binaries (workaround for npm bug)
        run: |
          cd frontend
          npm install @rollup/rollup-linux-x64-gnu --save-optional --force || true

      - name: Build project
        run: |
          npm run build:frontend
          npm run build:backend

      - name: Create Vercel Build Output structure
        run: |
          # Create output directories
          mkdir -p .vercel/output/static
          mkdir -p .vercel/output/functions
          
          # Copy frontend static files
          cp -r frontend/dist/* .vercel/output/static/
          
          # Create API functions in proper Vercel format
          # Each API function needs its own directory
          for func in search lyrics process; do
            mkdir -p .vercel/output/functions/api/$func.func
            cp api/$func.ts .vercel/output/functions/api/$func.func/index.ts
            # Copy package.json with dependencies for the function
            cp package.json .vercel/output/functions/api/$func.func/
            echo '{"runtime":"@vercel/node@3.0.0","handler":"index.ts","launcherType":"Nodejs"}' > .vercel/output/functions/api/$func.func/.vc-config.json
            # Copy node_modules to ensure dependencies are available
            cp -r node_modules .vercel/output/functions/api/$func.func/ 2>/dev/null || echo "No node_modules to copy"
          done
          
          # Create main config.json for Build Output API v3
          echo '{"version":3,"routes":[{"src":"/api/search","dest":"/api/search"},{"src":"/api/lyrics","dest":"/api/lyrics"},{"src":"/api/process","dest":"/api/process"},{"handle":"filesystem"},{"src":"/(.*)","dest":"/index.html"}]}' > .vercel/output/config.json

      - name: Deploy to Vercel
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          vercel-args: '--prod --prebuilt'

      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          VERCEL_URL: ${{ steps.vercel.outputs.url }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Deployment successful!**\n\n- **Preview URL**: ${process.env.VERCEL_URL}\n- **Production URL**: https://kashibotto.vercel.app`
            })

  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for deployment
        run: sleep 30

      - name: Test Frontend Health
        run: |
          echo "Testing frontend deployment..."
          # Add your project URL here after first deployment
          # curl -f https://kashibotto.vercel.app/ || exit 1

      - name: Test Backend Health
        run: |
          echo "Testing backend deployment..."
          # Add your project URL here after first deployment
          # curl -f https://kashibotto.vercel.app/api || exit 1

      - name: Test API Endpoints
        run: |
          echo "Testing API endpoints..."
          # Add your project URL here after first deployment
          # curl -f "https://kashibotto.vercel.app/api/search?q=君の名は" || exit 1

  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: [deploy, test-deployment]
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Success Notification
        run: |
          echo "🎉 Deployment successful!"
          echo "Frontend: https://kashibotto.vercel.app"
          echo "Backend: https://kashibotto.vercel.app/api"
          echo "Check Vercel dashboard for deployment status."
